// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonopolyTestTask.Database;

#nullable disable

namespace MonopolyTestTask.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("MonopolyTestTask.Entities.Box", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExperationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PalletId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ProductionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PalletId");

                    b.ToTable("Boxes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ExperationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 10,
                            Length = 5,
                            PalletId = 4,
                            ProductionDate = new DateTime(2004, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 10,
                            Width = 10
                        },
                        new
                        {
                            Id = 2,
                            ExperationDate = new DateTime(2025, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 10,
                            Length = 8,
                            PalletId = 4,
                            Weight = 10,
                            Width = 10
                        },
                        new
                        {
                            Id = 3,
                            ExperationDate = new DateTime(2010, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 10,
                            Length = 2,
                            PalletId = 3,
                            Weight = 10,
                            Width = 10
                        },
                        new
                        {
                            Id = 4,
                            ExperationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 10,
                            Length = 12,
                            PalletId = 3,
                            ProductionDate = new DateTime(2020, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 10,
                            Width = 17
                        },
                        new
                        {
                            Id = 5,
                            ExperationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 7,
                            Length = 5,
                            PalletId = 2,
                            ProductionDate = new DateTime(2019, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 10,
                            Width = 10
                        },
                        new
                        {
                            Id = 6,
                            ExperationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 10,
                            Length = 10,
                            PalletId = 2,
                            ProductionDate = new DateTime(2008, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 15,
                            Width = 10
                        },
                        new
                        {
                            Id = 7,
                            ExperationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 10,
                            Length = 1,
                            PalletId = 1,
                            ProductionDate = new DateTime(2015, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 11,
                            Width = 10
                        },
                        new
                        {
                            Id = 8,
                            ExperationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 10,
                            Length = 5,
                            PalletId = 4,
                            ProductionDate = new DateTime(2018, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 10,
                            Width = 2
                        },
                        new
                        {
                            Id = 9,
                            ExperationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 10,
                            Length = 7,
                            PalletId = 4,
                            ProductionDate = new DateTime(2018, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 10,
                            Width = 8
                        },
                        new
                        {
                            Id = 10,
                            ExperationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 10,
                            Length = 5,
                            PalletId = 4,
                            ProductionDate = new DateTime(2015, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 10,
                            Width = 10
                        },
                        new
                        {
                            Id = 11,
                            ExperationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 5,
                            Length = 7,
                            PalletId = 1,
                            ProductionDate = new DateTime(2015, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 10,
                            Width = 10
                        },
                        new
                        {
                            Id = 12,
                            ExperationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 15,
                            Length = 9,
                            PalletId = 3,
                            ProductionDate = new DateTime(2000, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 10,
                            Width = 10
                        },
                        new
                        {
                            Id = 13,
                            ExperationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 10,
                            Length = 4,
                            PalletId = 1,
                            ProductionDate = new DateTime(2000, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 10,
                            Width = 10
                        },
                        new
                        {
                            Id = 14,
                            ExperationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 10,
                            Length = 5,
                            PalletId = 2,
                            ProductionDate = new DateTime(2002, 10, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 12,
                            Width = 11
                        },
                        new
                        {
                            Id = 15,
                            ExperationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 10,
                            Length = 5,
                            PalletId = 1,
                            ProductionDate = new DateTime(2001, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Weight = 11,
                            Width = 12
                        });
                });

            modelBuilder.Entity("MonopolyTestTask.Entities.Pallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Pallets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Height = 40,
                            Length = 50,
                            Width = 40
                        },
                        new
                        {
                            Id = 2,
                            Height = 40,
                            Length = 50,
                            Width = 40
                        },
                        new
                        {
                            Id = 3,
                            Height = 40,
                            Length = 50,
                            Width = 40
                        },
                        new
                        {
                            Id = 4,
                            Height = 40,
                            Length = 50,
                            Width = 40
                        });
                });

            modelBuilder.Entity("MonopolyTestTask.Entities.Box", b =>
                {
                    b.HasOne("MonopolyTestTask.Entities.Pallet", "Pallet")
                        .WithMany("Boxes")
                        .HasForeignKey("PalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pallet");
                });

            modelBuilder.Entity("MonopolyTestTask.Entities.Pallet", b =>
                {
                    b.Navigation("Boxes");
                });
#pragma warning restore 612, 618
        }
    }
}
